"""Catálogos oficiales del SAT (descripciones).

Contienen los códigos usados en el CFDI 4.0 con su descripción, igual que
los catálogos c_* publicados por el SAT. Se usan para los reportes Excel
con paridad de columnas vs. Mi Admin XML.
"""

from __future__ import annotations

TIPO_COMPROBANTE: dict[str, str] = {
    "I": "Ingreso",
    "E": "Egreso",
    "T": "Traslado",
    "N": "Nómina",
    "P": "Pago",
}

METODO_PAGO: dict[str, str] = {
    "PUE": "Pago en una sola exhibición",
    "PPD": "Pago en parcialidades o diferido",
}

USO_CFDI: dict[str, str] = {
    "G01": "Adquisición de mercancías",
    "G02": "Devoluciones, descuentos o bonificaciones",
    "G03": "Gastos en general",
    "G04": "Construcciones",
    "G05": "Mobiliario y equipo de oficina por inversiones",
    "G06": "Equipo de transporte",
    "G07": "Equipo de cómputo y accesorios",
    "G08": "Dados, troqueles, moldes, matrices y herramental",
    "G09": "Comunicaciones telefónicas",
    "G10": "Comunicaciones satelitales",
    "G11": "Otra maquinaria y equipo",
    "G12": "Armamento y equipo de defensa",
    "G13": "Combustibles, lubricantes y aditivos",
    "G14": "Autopartes y accesorios para automóviles",
    "G15": "Artículos de limpieza",
    "G16": "Juguetes",
    "G17": "Mercancías vendidas a través de internet",
    "G18": "Gastos de transporte",
    "G19": "Gastos de traslado, hospedaje y manejo de mercancías",
    "G20": "Muebles, equipos de cómputo y accesorios (arrendamiento)",
    "G21": "Muebles, equipos de cómputo y accesorios (mantenimiento)",
    "G22": "Gastos de consumo o goce personal",
    "G23": "Recargos, penalizaciones o intereses",
    "G24": "Servicios de gestión",
    "G25": "Honorarios médicos, dentales y gastos hospitalarios",
    "G26": "Gastos funerarios",
    "G27": "Donativos",
    "G28": "Gastos hipotecarios",
    "G29": "Aportaciones voluntarias al SAR",
    "G30": "Gastos de carácter médico, dental u hospitalario",
    "G31": "Cuotas obrero patronales",
    "G32": "Colegiaturas",
    "G33": "Gastos por servicios profesionales (honorarios)",
    "G34": "Gastos por servicios médicos",
    "G35": "Gastos por servicios de veterinaria",
    "G36": "Gastos en alimentación",
    "G37": "Gastos de funeral",
    "G38": "Gastos de hospedaje",
    "G39": "Gastos por servicios de esparcimiento",
    "G40": "Gastos por servicios de salud",
    "G41": "Gastos por servicios de telecomunicaciones",
    "G42": "Gastos por servicios de energía eléctrica",
    "G43": "Gastos por servicios de agua",
    "G44": "Gastos por servicios de gas",
    "G45": "Gastos por servicios de internet",
    "G46": "Gastos por servicios de transportación",
    "G47": "Gastos por servicios de seguro",
    "G48": "Gastos por servicios de mantenimiento",
    "G49": "Gastos por servicios de educación",
    "G50": "Gastos por servicios de combate a la pobreza",
    "G51": "Gastos por servicios de vivienda",
    "G52": "Gastos por servicios de transporte",
    "G53": "Gastos por servicios de recreación",
    "G54": "Gastos por servicios de comunicación",
    "G55": "Gastos por servicios de información",
    "G56": "Gastos por servicios de asesoría",
    "G57": "Gastos por servicios de representación",
    "G58": "Gastos por servicios de gestión",
    "G59": "Gastos por servicios de administración",
    "G60": "Gastos por servicios de contabilidad",
    "G61": "Gastos por servicios de auditoría",
    "G62": "Gastos por servicios de legal",
    "G63": "Gastos por servicios de financiamiento",
    "G64": "Gastos por servicios de notaría",
    "G65": "Gastos por servicios de correduría",
    "G66": "Gastos por servicios de avalúo",
    "G67": "Gastos por servicios de peritaje",
    "G68": "Gastos por servicios de investigación",
    "G69": "Gastos por servicios de consultoría",
    "G70": "Gastos por servicios de asuntos corporativos",
    "G71": "Gastos por servicios de capital humano",
    "G72": "Gastos por servicios de logística",
    "G73": "Gastos por servicios de seguridad",
    "G74": "Gastos por servicios de limpieza",
    "G75": "Gastos por servicios de restaurante",
    "G76": "Gastos por servicios de coordinación",
    "G77": "Gastos por servicios de administración de riesgos",
    "G78": "Gastos por servicios de tecnología de la información",
    "G79": "Gastos por servicios de mercadotecnia",
    "G80": "Gastos por servicios de recursos humanos",
    "G81": "Gastos por servicios de ventas",
    "G82": "Gastos por servicios de compras",
    "G83": "Gastos por servicios de pagos",
    "G84": "Gastos por servicios de cobranza",
    "G85": "Gastos por servicios de impuestos",
    "G86": "Gastos por servicios de nómina",
    "G87": "Gastos por servicios de seguros",
    "G88": "Gastos por servicios de inversiones",
    "G89": "Gastos por servicios de proyectos",
    "G90": "Gastos por servicios de oficina",
    "G91": "Gastos por servicios de papelería",
    "G92": "Gastos por servicios de reproducción",
    "G93": "Gastos por servicios de envío",
    "G94": "Gastos por servicios de mensajería",
    "G95": "Gastos por servicios de almacenaje",
    "G96": "Gastos por servicios de distribución",
    "G97": "Gastos por servicios de importación",
    "G98": "Gastos por servicios de exportación",
    "G99": "Gastos por servicios de aduana",
    "P01": "Por definir",
    "S01": "Sin efectos fiscales",
    "CP01": "Pagos",
    "CN01": "Nómina",
    "D01": "Pagos a terceros",
    "D02": "Pagos a terceros (retención de ISR)",
    "D03": "Pagos a terceros (retención de IVA)",
    "D04": "Pagos por cuenta de terceros",
    "D05": "Pagos por cuenta de terceros (honorarios)",
    "D06": "Pagos por cuenta de terceros (arrendamiento)",
    "D07": "Pagos por cuenta de terceros (intereses)",
    "D08": "Pagos por cuenta de terceros (comisiones)",
    "D09": "Pagos por cuenta de terceros (dietas)",
    "D10": "Pagos por cuenta de terceros (viáticos)",
    "D11": "Pagos por cuenta de terceros (gastos)",
    "D12": "Pagos por cuenta de terceros (adquisiciones)",
    "D13": "Pagos por cuenta de terceros (servicios)",
    "D14": "Pagos por cuenta de terceros (seguros)",
    "D15": "Pagos por cuenta de terceros (fletes)",
    "D16": "Pagos por cuenta de terceros (honorarios médicos)",
    "D17": "Pagos por cuenta de terceros (intereses hipotecarios)",
    "D18": "Pagos por cuenta de terceros (aportaciones SAR)",
    "D19": "Pagos por cuenta de terceros (cuotas obrero patronales)",
    "D20": "Pagos por cuenta de terceros (colegiaturas)",
    "D21": "Pagos por cuenta de terceros (donativos)",
    "D22": "Pagos por cuenta de terceros (gastos funerarios)",
    "D23": "Pagos por cuenta de terceros (gastos médicos)",
    "D24": "Pagos por cuenta de terceros (previsión social)",
    "D25": "Pagos por cuenta de terceros (transporte escolar)",
    "D26": "Pagos por cuenta de terceros (erge de energía eléctrica)",
    "D27": "Pagos por cuenta de terceros (agua)",
    "D28": "Pagos por cuenta de terceros (gas)",
    "D29": "Pagos por cuenta de terceros (internet)",
    "D30": "Pagos por cuenta de terceros (telefonía)",
    "D31": "Pagos por cuenta de terceros (televisión)",
    "D32": "Pagos por cuenta de terceros (seguros de gastos médicos)",
    "D33": "Pagos por cuenta de terceros (seguros de vida)",
    "D34": "Pagos por cuenta de terceros (seguros de automóviles)",
    "D35": "Pagos por cuenta de terceros (seguros de daños)",
    "D36": "Pagos por cuenta de terceros (seguros de responsabilidad civil)",
    "D37": "Pagos por cuenta de terceros (seguros de transporte)",
    "D38": "Pagos por cuenta de terceros (seguros de caución)",
    "D39": "Pagos por cuenta de terceros (seguros de crédito)",
    "D40": "Pagos por cuenta de terceros (seguros de fianza)",
    "I01": "Construcciones",
    "I02": "Mobiliario y equipo de oficina por inversiones",
    "I03": "Equipo de transporte",
    "I04": "Equipo de cómputo y accesorios",
    "I05": "Dados, troqueles, moldes, matrices y herramental",
    "I06": "Comunicaciones telefónicas",
    "I07": "Comunicaciones satelitales",
    "I08": "Otra maquinaria y equipo",
    "I09": "Armamento y equipo de defensa",
    "I10": "Combustibles, lubricantes y aditivos",
    "I11": "Autopartes y accesorios para automóviles",
    "I12": "Artículos de limpieza",
    "I13": "Juguetes",
    "I14": "Mercancías vendidas a través de internet",
    "I15": "Gastos de transporte",
    "I16": "Gastos de traslado, hospedaje y manejo de mercancías",
    "I17": "Muebles, equipos de cómputo y accesorios (arrendamiento)",
    "I18": "Muebles, equipos de cómputo y accesorios (mantenimiento)",
    "I19": "Gastos de consumo o goce personal",
    "I20": "Recargos, penalizaciones o intereses",
    "I21": "Servicios de gestión",
    "I22": "Honorarios médicos, dentales y gastos hospitalarios",
    "I23": "Gastos funerarios",
    "I24": "Donativos",
    "I25": "Gastos hipotecarios",
    "I26": "Aportaciones voluntarias al SAR",
    "I27": "Gastos de carácter médico, dental u hospitalario",
    "I28": "Cuotas obrero patronales",
    "I29": "Colegiaturas",
    "I30": "Gastos por servicios profesionales (honorarios)",
    "I31": "Gastos por servicios médicos",
    "I32": "Gastos por servicios de veterinaria",
    "I33": "Gastos en alimentación",
    "I34": "Gastos de funeral",
    "I35": "Gastos de hospedaje",
    "I36": "Gastos por servicios de esparcimiento",
    "I37": "Gastos por servicios de salud",
    "I38": "Gastos por servicios de telecomunicaciones",
    "I39": "Gastos por servicios de energía eléctrica",
    "I40": "Gastos por servicios de agua",
    "I41": "Gastos por servicios de gas",
    "I42": "Gastos por servicios de internet",
    "I43": "Gastos por servicios de transportación",
    "I44": "Gastos por servicios de seguro",
    "I45": "Gastos por servicios de mantenimiento",
    "I46": "Gastos por servicios de educación",
}

REGIMEN_FISCAL: dict[str, str] = {
    "601": "General de Ley Personas Morales",
    "603": "Personas Morales con Fines no Lucrativos",
    "605": "Sueldos y Salarios e Ingresos Asimilados a Salarios",
    "606": "Arrendamiento",
    "607": "Régimen de Enajenación o Adquisición de Bienes",
    "608": "Demás ingresos",
    "609": "Consolidación",
    "610": "Residentes en el Extranjero sin Establecimiento Permanente en México",
    "611": "Ingresos por Dividendos (socios y accionistas)",
    "612": "Personas Físicas con Actividades Empresariales y Profesionales",
    "613": "Ingresos por intereses",
    "614": "Ingresos por arrendamiento",
    "615": "Demás ingresos",
    "616": "Sin obligaciones fiscales",
    "620": "Sociedades Cooperativas de Producción",
    "621": "Incorporación Fiscal",
    "622": "Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras",
    "623": "Opcional para Grupos de Sociedades",
    "624": "Coordinados",
    "625": "Régimen de las Actividades Empresariales con Ingresos a través de Plataformas Tecnológicas",
    "626": "Régimen Simplificado de Confianza",
    "628": "Hidrocarburos",
    "629": "De los regímenes fiscales preferentes y de las empresas multinacionales",
    "630": "Enajenación de acciones en bolsa de valores",
    "631": "Régimen de las empresas que tributan en el extranjero",
}

FORMA_PAGO: dict[str, str] = {
    "01": "Efectivo",
    "02": "Cheque nominativo",
    "03": "Transferencia electrónica de fondos",
    "04": "Tarjeta de crédito",
    "05": "Monedero electrónico",
    "06": "Dinero electrónico",
    "08": "Vales de despensa",
    "12": "Dación en pago",
    "13": "Pago por subrogación",
    "14": "Pago por consignación",
    "15": "Condonación",
    "17": "Compensación",
    "23": "Novación",
    "24": "Confusión",
    "25": "Remisión de deuda",
    "26": "Prescripción o caducidad",
    "27": "A satisfacción del acreedor",
    "28": "Tarjeta de débito",
    "29": "Tarjeta de servicios",
    "30": "Aplicación de anticipos",
    "31": "Intermediario pagos",
    "32": "Pagos con tarjeta de crédito",
    "99": "Por definir",
}


def describir(catalogo: dict[str, str], codigo: str | None) -> str:
    """Devuelve 'CÓDIGO - Descripción' o el código solo si no está en el catálogo."""
    if not codigo:
        return ""
    descripcion = catalogo.get(codigo)
    return f"{codigo} - {descripcion}" if descripcion else codigo