"""Definiciones de columnas y vistas de la tabla (extraído de pantalla_admin)."""

from __future__ import annotations

MODO_CFDI40 = "cfdi40"
MODO_PAGOS = "pagos"
MODO_NOMINA = "nomina"

_COLUMNAS_CFDI40 = [
    ("verificado", "Verificado o Asoc", 110),
    ("estatus", "Estado SAT", 100),
    ("es_cancelable", "EsCancelable", 110),
    ("estatus_cancelacion", "EstatusCancelacion", 140),
    ("relaciones", "CfdiRelacionados", 160),
    ("uuid", "UUID", 240),
    ("serie", "Serie", 60),
    ("folio", "Folio", 70),
    ("version", "Version", 60),
    ("tipo", "TipoComprobante", 110),
    ("fecha_timbrado", "FechaTimbradoXML", 140),
    ("fecha", "FechaEmisionXML", 140),
    ("lugar_expedicion", "LugarDeExpedicion", 110),
    ("emisor_rfc", "RFC Emisor", 110),
    ("emisor", "Nombre Emisor", 180),
    ("emisor_regimen", "RegimenFiscal", 140),
    ("receptor_rfc", "RFC Receptor", 110),
    ("receptor", "Nombre Receptor", 180),
    ("uso_cfdi", "UsoCFDI", 160),
    ("regimen_fiscal_receptor", "RegimenFiscalReceptor", 160),
    ("domicilio_fiscal_receptor", "DomicilioFiscalReceptor", 140),
    ("forma_pago", "FormaDePago", 140),
    ("metodo_pago", "Metodo de Pago", 120),
    ("complementos", "Complementos comprobante", 160),
    ("conceptos", "Conceptos", 220),
    ("complementos_conceptos", "Complementos conceptos", 140),
    ("subtotal", "SubTotal", 90),
    ("descuento", "Descuento", 90),
    ("total_traslados", "Total Trasladados", 100),
    ("total_retenciones", "Total Retenidos", 100),
    ("total", "Total", 100),
    ("moneda", "Moneda", 60),
    ("iva_exento", "IVA Exento Base", 90),
    ("iva_cero", "IVA Cero Base", 90),
    ("iva_8", "IVA 8 Importe", 90),
    ("iva_16", "IVA 16 Importe", 90),
    ("isr_ret", "ISR Retenido", 90),
    ("iva_ret", "IVA Retenido", 90),
    ("ieps_ret", "IEPS Retenido", 90),
    ("ret_isr_125", "Ret ISR 1.25 Importe", 100),
    ("ret_iva_106", "Ret IVA 10.6667 Importe", 110),
    ("ret_iva_8", "Ret IVA 8 Importe", 90),
    ("ret_iva_6", "Ret IVA 6 Importe", 90),
    ("ret_iva_16", "Ret IVA 16 Importe", 90),
    ("no_cert_sat", "No Certificado SAT", 140),
    ("no_cert_emisor", "No Certificado Emisor", 140),
    ("ruta", "Archivo XML", 200),
]

_COLUMNAS_PAGOS_CONCILIACION = [
    ("cliente", "Cliente", 120),
    ("uuid_rep", "UUID REP", 240),
    ("serie_rep", "Serie REP", 60),
    ("folio_rep", "Folio REP", 70),
    ("fecha_rep", "Fecha REP", 130),
    ("estatus_rep", "Estatus REP", 100),
    ("fecha_pago", "Fecha Pago", 130),
    ("forma_pago", "Forma Pago", 140),
    ("moneda_pago", "Moneda Pago", 70),
    ("monto", "Monto", 90),
    ("num_operacion", "Núm. Operación", 100),
    ("cta_origen", "Cuenta Origen", 110),
    ("cta_destino", "Cuenta Destino", 110),
    ("rfc_cta_origen", "RFC Cta Origen", 110),
    ("uuid_doc", "UUID Factura", 240),
    ("serie", "Serie", 60),
    ("folio", "Folio", 70),
    ("moneda_dr", "Moneda DR", 70),
    ("parcialidad", "Parcialidad", 60),
    ("saldo_ant", "Saldo Anterior", 95),
    ("pagado", "Pagado", 95),
    ("saldo_insoluto", "Saldo Insoluto", 95),
    ("estatus_factura", "Estatus Factura", 100),
    ("estatus_consultado", "Estatus consultado", 110),
    ("es_cancelable_rep", "EsCancelable REP", 110),
    ("estatus_cancelacion_rep", "EstatusCancelacion REP", 140),
    ("fecha_timbrado_rep", "FechaTimbrado REP", 130),
    ("tipo_comprobante_rep", "TipoComprobante REP", 110),
    ("ruta_rep", "Archivo XML REP", 180),
    ("es_cancelable", "EsCancelable", 110),
    ("estatus_cancelacion", "EstatusCancelacion", 140),
    ("fecha_timbrado", "FechaTimbradoXML", 130),
    ("tipo_comprobante", "TipoComprobante", 110),
    ("total_factura", "Total Factura", 95),
    ("ruta", "Archivo XML", 180),
]

_COLUMNAS_NOMINA = [
    ("cliente", "Cliente", 120),
    ("estatus", "Estado SAT", 100),
    ("es_cancelable", "EsCancelable", 110),
    ("estatus_cancelacion", "EstatusCancelacion", 140),
    ("uuid", "UUID", 240),
    ("serie", "Serie", 60),
    ("folio", "Folio", 70),
    ("fecha_timbrado", "FechaTimbradoXML", 130),
    ("fecha", "FechaEmisionXML", 130),
    ("emisor_rfc", "RFC Emisor", 110),
    ("emisor_nombre", "Nombre Emisor", 180),
    ("registro_patronal", "Registro Patronal", 120),
    ("receptor_rfc", "RFC Receptor", 110),
    ("receptor_nombre", "Nombre Receptor", 180),
    ("curp", "CURP", 140),
    ("num_empleado", "Num Empleado", 90),
    ("puesto", "Puesto", 140),
    ("tipo_nomina", "Tipo Nomina", 90),
    ("fecha_pago", "Fecha Pago", 110),
    ("fecha_inicial_pago", "Fecha Inicial Pago", 110),
    ("fecha_final_pago", "Fecha Final Pago", 110),
    ("num_dias_pagados", "Num Dias Pagados", 90),
    ("periodicidad_pago", "Periodicidad Pago", 110),
    ("total_percepciones", "Total Percepciones", 100),
    ("total_deducciones", "Total Deducciones", 100),
    ("total_otros_pagos", "Total Otros Pagos", 100),
    ("subtotal", "SubTotal", 90),
    ("descuento", "Descuento", 90),
    ("total", "Total", 90),
    ("moneda", "Moneda", 60),
    ("ruta", "Archivo XML", 180),
]

# ── Vistas de Conciliación de Pagos (estilo Mi Admin XML) ────────────────────

VISTAS_PAGOS = [
    ("conciliacion", "Conciliación"),
    ("facturas_ppd", "Facturas PPD"),
    ("facturas_p", "Facturas P"),
    ("pagos", "Pagos"),
    ("doctos", "DoctosRelacionados"),
]

_COLUMNAS_FACTURAS_PPD = [
    ("cliente", "Cliente", 120),
    ("estatus", "Estado SAT", 100),
    ("es_cancelable", "EsCancelable", 110),
    ("estatus_cancelacion", "EstatusCancelacion", 140),
    ("uuid", "UUID", 240),
    ("serie", "Serie", 60),
    ("folio", "Folio", 70),
    ("fecha", "FechaEmisionXML", 140),
    ("fecha_timbrado", "FechaTimbradoXML", 140),
    ("emisor_rfc", "RFC Emisor", 110),
    ("emisor_nombre", "Nombre Emisor", 180),
    ("receptor_rfc", "RFC Receptor", 110),
    ("receptor_nombre", "Nombre Receptor", 180),
    ("moneda", "Moneda", 60),
    ("total", "Total", 100),
    ("pagado", "Pagado", 100),
    ("saldo_pendiente", "Saldo Pendiente", 110),
    ("estado_cobranza", "Estatus de Pago", 150),
    ("ruta", "Archivo XML", 200),
]

_COLUMNAS_FACTURAS_P = [
    ("cliente", "Cliente", 120),
    ("estatus", "Estado SAT", 100),
    ("es_cancelable", "EsCancelable", 110),
    ("estatus_cancelacion", "EstatusCancelacion", 140),
    ("uuid", "UUID", 240),
    ("serie", "Serie", 60),
    ("folio", "Folio", 70),
    ("fecha", "FechaEmisionXML", 140),
    ("fecha_timbrado", "FechaTimbradoXML", 140),
    ("emisor_rfc", "RFC Emisor", 110),
    ("emisor_nombre", "Nombre Emisor", 180),
    ("receptor_rfc", "RFC Receptor", 110),
    ("receptor_nombre", "Nombre Receptor", 180),
    ("moneda", "Moneda", 60),
    ("total", "Total", 100),
    ("num_pagos", "Núm. Pagos", 90),
    ("monto_pagos", "Monto Pagado", 110),
    ("ruta", "Archivo XML", 200),
]

_COLUMNAS_PAGOS_LISTA = [
    ("cliente", "Cliente", 120),
    ("uuid_rep", "UUID REP", 240),
    ("serie_rep", "Serie REP", 60),
    ("folio_rep", "Folio REP", 70),
    ("estatus_rep", "Estado SAT REP", 100),
    ("fecha_pago", "Fecha Pago", 130),
    ("forma_pago", "Forma Pago", 140),
    ("moneda", "Moneda", 70),
    ("monto", "Monto", 100),
    ("num_operacion", "Núm. Operación", 110),
    ("cta_origen", "Cuenta Origen", 130),
    ("cta_destino", "Cuenta Destino", 130),
    ("rfc_cta_origen", "RFC Cta Origen", 120),
    ("num_doctos", "Núm. Doctos", 90),
]

_COLUMNAS_DOCTOS = [
    ("cliente", "Cliente", 120),
    ("estatus_factura", "Estado SAT", 100),
    ("no_cert_emisor", "No Certificado Emisor", 140),
    ("no_cert_sat", "No Certificado SAT", 140),
    ("fecha_emision", "Fecha Emision", 140),
    ("fecha_timbrado", "Fecha Timbrado", 140),
    ("anio", "Año", 55),
    ("mes", "Mes", 50),
    ("dia", "Día", 50),
    ("serie", "Serie", 60),
    ("folio", "Folio", 70),
    ("uuid_doc", "UUID", 240),
    ("rfc_emisor", "RFC Emisor", 110),
    ("nombre_emisor", "Nombre Emisor", 180),
    ("regimen_fiscal", "RegimenFiscal", 140),
    ("fecha_pago", "Fecha Pago", 130),
    ("forma_pago", "Forma Pago", 130),
    ("monto", "Monto Pago", 90),
    ("parcialidad", "Parcialidad", 80),
    ("saldo_ant", "Saldo Anterior", 100),
    ("pagado", "Pagado", 100),
    ("saldo_insoluto", "Saldo Insoluto", 100),
    ("uuid_rep", "UUID REP", 240),
    ("serie_rep", "Serie REP", 60),
    ("folio_rep", "Folio REP", 70),
    ("ruta", "Archivo XML Factura", 200),
]
